steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--platform"
      - "linux/amd64"
      - "-t"
      - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/si2-sgd-hc-backend:$COMMIT_SHA"
      - "-f"
      - "Dockerfile.deploy"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/si2-sgd-hc-backend:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "si2-sgd-hc-backend"
      - "--image"
      - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/si2-sgd-hc-backend:$COMMIT_SHA"
      - "--region"
      - "southamerica-east1"
      - "--platform"
      - "managed"
      - "--quiet"

images:
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/si2-sgd-hc-backend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
