spring.application.name=sgd_hc
spring.config.import=optional:file:.env[.properties]

# ===================================================================
# 0. SERVER
# ===================================================================
server.port=${PORT:8080}
server.max-http-header-size=8KB


# ===================================================================
# 1. CONFIGURACIÓN BASE DE DATOS
# ===================================================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sgd_hc}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===================================================================
# 2. JPA / HIBERNATE
# ===================================================================
# IMPORTANTE: usar 'none' con Flyway
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Prod
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=false


# ===================================================================
# 3. FLYWAY (Migraciones de Base de Datos)
# ===================================================================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration/main
spring.flyway.baseline-version=0
spring.flyway.validate-on-migrate=true
#Prod
#spring.flyway.validate-on-migrate=false

# ===================================================================
# 4. JWT & SEGURIDAD
# ===================================================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://calm-wave-000d39410.7.azurestaticapps.net}
logging.level.org.springframework.security=TRACE

# ===================================================================
# 4.1. REDIS 
# ===================================================================
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.password=
#spring.data.redis.timeout=5000ms

# ===================================================================
# 5. OPENAPI / SWAGGER & OTROS
# ===================================================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.show-actuator=true
ocr.service.url=${OCR_SERVICE_URL:http://localhost:8001}

# H2 Console (Opcional, solo si usas H2 en algún momento para pruebas)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===================================================================
# 6. ALMACENAMIENTO DE ARCHIVOS
# ===================================================================
storage.upload-dir=${UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=500MB

# Tomcat embebido: eliminar límites propios que bloquean uploads grandes
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1


# ===================================================================
# 8. CONFIGURACIÓN SEMILLA (SUPERUSER & DEFAULT)
# ===================================================================
app.seed.system.slug=${SYSTEM_SUPERUSER_SLUG:system}
app.seed.system.name=${SYSTEM_SUPERUSER_NAME:SGD Sistema Central}
app.seed.system.username=${SYSTEM_SUPERUSER_USERNAME:superuser.system}
app.seed.system.password=${SYSTEM_SUPERUSER_PASSWORD:superuser123}
app.seed.system.email=${SYSTEM_SUPERUSER_EMAIL:admin@sgd-sistema.com}
app.seed.system.firstName=${SYSTEM_SUPERUSER_FIRST_NAME:Super}
app.seed.system.lastName=${SYSTEM_SUPERUSER_LAST_NAME:User}
app.seed.system.nationalId=${SYSTEM_SUPERUSER_ID:0000000}

app.seed.default.slug=${DEFAULT_SLUG:default}
app.seed.default.name=${DEFAULT_NAME:Hospital General (Demo)}
app.seed.default.username=${DEFAULT_USERNAME:admin.default}
app.seed.default.password=${DEFAULT_PASSWORD:admin123}
app.seed.default.email=${DEFAULT_EMAIL:admin@hospital.com}
app.seed.default.firstName=${DEFAULT_ADMIN_FIRST_NAME:Admin}
app.seed.default.lastName=${DEFAULT_ADMIN_LAST_NAME:Limited}
app.seed.default.nationalId=${DEFAULT_ADMIN_ID:1111111}

# ===================================================================
# 9. AZURE STORAGE
# ===================================================================
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING:}
azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME:uploads}
logging.level.com.sgd_hc=DEBUG

# ===================================================================
# 10. AUDITORIA
# ===================================================================
audit.encryption.key=${AUDIT_ENCRYPTION_KEY:Lk+JyPYKgx7Ooxz6kYCU1/A7pZOQb+iz0B4qc3qHHgg=}
audit.integrity.key=${AUDIT_INTEGRITY_KEY:SZE2vlhEUJVF8svvD4hG0xigvh1MML2WRGB2z7bimkZvsPqpPWkNzJk2oZXTKfkp}

audit.datasource.url=${DB_URL_AUDIT:jdbc:postgresql://localhost:5432/sgd_hc_audit}
audit.datasource.username=${DB_USERNAME_AUDIT:postgres}
audit.datasource.password=${DB_PASSWORD_AUDIT:postgres}

# PROFILES
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.cloud.gcp.logging.enabled=${GCP_LOGGING_ENABLED:false}  
spring.cloud.gcp.logging.project-id=${GCP_PROJECT_ID:si2-sgd-hc}

audit.async.enabled=${AUDIT_ASYNC_ENABLED:true}
audit.async.pool.size=${AUDIT_ASYNC_POOL_SIZE:4}

audit.exclude.paths=/api/schema,/api-docs,/swagger,/health,/metrics,/static

audit.trusted-proxies=${AUDIT_TRUSTED_PROXIES:}
audit.buffer.max-size=${AUDIT_BUFFER_MAX_SIZE:10000}

# ===================================================================
# 11. MAIL
# ===================================================================
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${SPRING_MAIL_FROM:}
spring.mail.group-copy=${SPRING_MAIL_GROUP_COPY:sgd_hc@googlegroups.com}
