-- =============================================================================
-- V11 — INSERTAR PERMISOS POR DEFECTO
-- =============================================================================

INSERT INTO permissions (name, module, action, description) VALUES
-- Tenant
('tenant:read',          'tenant', 'read', 'Permiso para tenant:read'),
('tenant:read:id',       'tenant', 'read', 'Permiso para tenant:read:id'),
('tenant:read:name',     'tenant', 'read', 'Permiso para tenant:read:name'),
('tenant:read:slug',     'tenant', 'read', 'Permiso para tenant:read:slug'),
('tenant:read:email',    'tenant', 'read', 'Permiso para tenant:read:email'),
('tenant:read:phone',    'tenant', 'read', 'Permiso para tenant:read:phone'),
('tenant:read:address',  'tenant', 'read', 'Permiso para tenant:read:address'),
('tenant:read:logo_url', 'tenant', 'read', 'Permiso para tenant:read:logo_url'),
('tenant:read:settings', 'tenant', 'read', 'Permiso para tenant:read:settings'),
('tenant:read:subscription_plan',       'tenant', 'read', 'Permiso para tenant:read:subscription_plan'),
('tenant:read:subscription_status',     'tenant', 'read', 'Permiso para tenant:read:subscription_status'),
('tenant:read:subscription_start_date', 'tenant', 'read', 'Permiso para tenant:read:subscription_start_date'),
('tenant:read:created_at',  'tenant', 'read', 'Permiso para tenant:read:created_at'),
('tenant:read:updated_at',  'tenant', 'read', 'Permiso para tenant:read:updated_at'),

('tenant:create',           'tenant', 'create', 'Permiso para tenant:create'),
('tenant:create:phone',     'tenant', 'create', 'Permiso para tenant:create:phone'),
('tenant:create:address',   'tenant', 'create', 'Permiso para tenant:create:address'),
('tenant:create:logo_url',  'tenant', 'create', 'Permiso para tenant:create:logo_url'),
('tenant:create:settings',  'tenant', 'create', 'Permiso para tenant:create:settings'),
('tenant:create:subscription_plan',       'tenant', 'create', 'Permiso para tenant:create:subscription_plan'),
('tenant:create:subscription_status',     'tenant', 'create', 'Permiso para tenant:create:subscription_status'),
('tenant:create:subscription_start_date', 'tenant', 'create', 'Permiso para tenant:create:subscription_start_date'),

('tenant:update',          'tenant', 'update', 'Permiso para tenant:update'),
('tenant:update:name',     'tenant', 'update', 'Permiso para tenant:update:name'),
('tenant:update:slug',     'tenant', 'update', 'Permiso para tenant:update:slug'),
('tenant:update:email',    'tenant', 'update', 'Permiso para tenant:update:email'),
('tenant:update:phone',    'tenant', 'update', 'Permiso para tenant:update:phone'),
('tenant:update:address',  'tenant', 'update', 'Permiso para tenant:update:address'),
('tenant:update:logo_url', 'tenant', 'update', 'Permiso para tenant:update:logo_url'),
('tenant:update:settings', 'tenant', 'update', 'Permiso para tenant:update:settings'),
('tenant:update:subscription_plan',       'tenant', 'update', 'Permiso para tenant:update:subscription_plan'),
('tenant:update:subscription_status',     'tenant', 'update', 'Permiso para tenant:update:subscription_status'),
('tenant:update:subscription_start_date', 'tenant', 'update', 'Permiso para tenant:update:subscription_start_date'),

('tenant:delete',          'tenant', 'delete', 'Permiso para tenant:delete'),


-- ################ Role ################
('role:read',             'role', 'read', 'Permiso para role:read'),
('role:read:id',          'role', 'read', 'Permiso para role:read:id'),
('role:read:name',        'role', 'read', 'Permiso para role:read:name'),
('role:read:description', 'role', 'read', 'Permiso para role:read:description'),
('role:read:is_active',   'role', 'read', 'Permiso para role:read:is_active'),
('role:read:permissions', 'role', 'read', 'Permiso para role:read:permissions'),
('role:read:created_at',  'role', 'read', 'Permiso para role:read:created_at'),
('role:read:updated_at',  'role', 'read', 'Permiso para role:read:updated_at'),

('role:create',             'role', 'create', 'Permiso para role:create'),
('role:create:description', 'role', 'create', 'Permiso para role:create:description'),
('role:create:permissions', 'role', 'create', 'Permiso para role:create:permissions'),

('role:update',             'role', 'update', 'Permiso para role:update'),
('role:update:name',        'role', 'update', 'Permiso para role:update:name'),
('role:update:description', 'role', 'update', 'Permiso para role:update:description'),
('role:update:is_active',   'role', 'update', 'Permiso para role:update:is_active'),
('role:update:permissions', 'role', 'update', 'Permiso para role:update:permissions'),

('role:delete',             'role', 'delete', 'Permiso para role:delete'),

-- ################ User ################
('user:read',               'user', 'read', 'Permiso para user:read'),
('user:read:id',            'user', 'read', 'Permiso para user:read:id'),
('user:read:document_type', 'user', 'read', 'Permiso para user:read:document_type'),
('user:read:document_number', 'user', 'read', 'Permiso para user:read:document_number'),
('user:read:username',      'user', 'read', 'Permiso para user:read:username'),
('user:read:first_name',    'user', 'read', 'Permiso para user:read:first_name'),
('user:read:last_name',     'user', 'read', 'Permiso para user:read:last_name'),
('user:read:email',         'user', 'read', 'Permiso para user:read:email'),
('user:read:phone',         'user', 'read', 'Permiso para user:read:phone'),
('user:read:gender',        'user', 'read', 'Permiso para user:read:gender'),
('user:read:is_active',     'user', 'read', 'Permiso para user:read:is_active'),
('user:read:roles',         'user', 'read', 'Permiso para user:read:roles'),
('user:read:created_at',    'user', 'read', 'Permiso para user:read:created_at'),
('user:read:updated_at',    'user', 'read', 'Permiso para user:read:updated_at'),

('user:create',        'user', 'create', 'Permiso para user:create'),
('user:create:phone',  'user', 'create', 'Permiso para user:create:phone'),
('user:create:gender', 'user', 'create', 'Permiso para user:create:gender'),
('user:create:roles',  'user', 'create', 'Permiso para user:create:roles'),

('user:update',                 'user', 'update', 'Permiso para user:update'),
('user:update:document_type',   'user', 'update', 'Permiso para user:update:document_type'),
('user:update:document_number', 'user', 'update', 'Permiso para user:update:document_number'),
('user:update:first_name',      'user', 'update', 'Permiso para user:update:first_name'),
('user:update:last_name', 'user', 'update', 'Permiso para user:update:last_name'),
('user:update:email',     'user', 'update', 'Permiso para user:update:email'),
('user:update:password',  'user', 'update', 'Permiso para user:update:password'),
('user:update:phone',     'user', 'update', 'Permiso para user:update:phone'),
('user:update:gender',    'user', 'update', 'Permiso para user:update:gender'),
('user:update:is_active', 'user', 'update', 'Permiso para user:update:is_active'),
('user:update:roles',     'user', 'update', 'Permiso para user:update:roles'),

('user:delete', 'user', 'delete', 'Permiso para user:delete'),

-- ################ Patient ################
('patient:read',            'patient', 'read', 'Permiso para patient:read'),
('patient:read:id',         'patient', 'read', 'Permiso para patient:read:id'),
('patient:read:document_type',   'patient', 'read', 'Permiso para patient:read:document_type'),
('patient:read:document_number', 'patient', 'read', 'Permiso para patient:read:document_number'),
('patient:read:first_name', 'patient', 'read', 'Permiso para patient:read:first_name'),
('patient:read:last_name',  'patient', 'read', 'Permiso para patient:read:last_name'),
('patient:read:birth_date', 'patient', 'read', 'Permiso para patient:read:birth_date'),
('patient:read:gender',     'patient', 'read', 'Permiso para patient:read:gender'),
('patient:read:phone',      'patient', 'read', 'Permiso para patient:read:phone'),
('patient:read:address',    'patient', 'read', 'Permiso para patient:read:address'),
('patient:read:created_at', 'patient', 'read', 'Permiso para patient:read:created_at'),
('patient:read:updated_at', 'patient', 'read', 'Permiso para patient:read:updated_at'),

('patient:create',         'patient', 'create', 'Permiso para patient:create'),
('patient:create:document_type',   'patient', 'create', 'Permiso para patient:create:document_type'),
('patient:create:document_number', 'patient', 'create', 'Permiso para patient:create:document_number'),
('patient:create:gender',  'patient', 'create', 'Permiso para patient:create:gender'),
('patient:create:phone',   'patient', 'create', 'Permiso para patient:create:phone'),
('patient:create:address', 'patient', 'create', 'Permiso para patient:create:address'),

('patient:update',            'patient', 'update', 'Permiso para patient:update'),
('patient:update:document_type',   'patient', 'update', 'Permiso para patient:update:document_type'),
('patient:update:document_number', 'patient', 'update', 'Permiso para patient:update:document_number'),
('patient:update:first_name', 'patient', 'update', 'Permiso para patient:update:first_name'),
('patient:update:last_name',  'patient', 'update', 'Permiso para patient:update:last_name'),
('patient:update:birth_date', 'patient', 'update', 'Permiso para patient:update:birth_date'),
('patient:update:gender',     'patient', 'update', 'Permiso para patient:update:gender'),
('patient:update:phone',      'patient', 'update', 'Permiso para patient:update:phone'),
('patient:update:address',    'patient', 'update', 'Permiso para patient:update:address'),

('patient:delete', 'patient', 'delete', 'Permiso para patient:delete'),

-- ################ Document ################
('document:read',             'document', 'read', 'Permiso para document:read'),
('document:read:id',          'document', 'read', 'Permiso para document:read:id'),
('document:read:patient_id',  'document', 'read', 'Permiso para document:read:patient_id'),
('document:read:uploader_id', 'document', 'read', 'Permiso para document:read:uploader_id'),
('document:read:template_id', 'document', 'read', 'Permiso para document:read:template_id'),
('document:read:status',      'document', 'read', 'Permiso para document:read:status'),
('document:read:is_external_source', 'document', 'read', 'Permiso para document:read:is_external_source'),
('document:read:clinical_content',   'document', 'read', 'Permiso para document:read:clinical_content'),
('document:read:file_url',       'document', 'read', 'Permiso para document:read:file_url'),
('document:read:issue_date',     'document', 'read', 'Permiso para document:read:issue_date'),
('document:read:expiry_date',    'document', 'read', 'Permiso para document:read:expiry_date'),
('document:read:version_number', 'document', 'read', 'Permiso para document:read:version_number'),
('document:read:created_at',     'document', 'read', 'Permiso para document:read:created_at'),
('document:read:updated_at',     'document', 'read', 'Permiso para document:read:updated_at'),

('document:create',                'document', 'create', 'Permiso para document:create'),
('document:create:template_id',    'document', 'create', 'Permiso para document:create:template_id'),
('document:create:status',         'document', 'create', 'Permiso para document:create:status'),
('document:create:is_external_source',  'document', 'create', 'Permiso para document:create:is_external_source'),
('document:create:clinical_content',    'document', 'create', 'Permiso para document:create:clinical_content'),
('document:create:file_url',       'document', 'create', 'Permiso para document:create:file_url'),
('document:create:expiry_date',    'document', 'create', 'Permiso para document:create:expiry_date'),
('document:create:version_number', 'document', 'create', 'Permiso para document:create:version_number'),

('document:update',             'document', 'update', 'Permiso para document:update'),
('document:update:issue_date',  'document', 'update', 'Permiso para document:update:issue_date'),
('document:update:expiry_date', 'document', 'update', 'Permiso para document:update:expiry_date'),
('document:update:status',      'document', 'update', 'Permiso para document:update:status'),
('document:update:clinical_content', 'document', 'update', 'Permiso para document:update:clinical_content'),
('document:update:file_url',    'document', 'update', 'Permiso para document:update:file_url'),

('document:delete', 'document', 'delete', 'Permiso para document:delete'),

-- ################ Document OCR Metadata ################
('document_ocr:read',             'document_ocr', 'read', 'Permiso para document_ocr:read'),
('document_ocr:read:document_id', 'document_ocr', 'read', 'Permiso para document_ocr:read:document_id'),
('document_ocr:read:raw_text',    'document_ocr', 'read', 'Permiso para document_ocr:read:raw_text'),
('document_ocr:read:datos_estructurados', 'document_ocr', 'read', 'Permiso para document_ocr:read:datos_estructurados'),
('document_ocr:read:confidence_score',    'document_ocr', 'read', 'Permiso para document_ocr:read:confidence_score'),
('document_ocr:read:pages_processed',     'document_ocr', 'read', 'Permiso para document_ocr:read:pages_processed'),
('document_ocr:read:file_type',   'document_ocr', 'read', 'Permiso para document_ocr:read:file_type'),
('document_ocr:read:created_at',  'document_ocr', 'read', 'Permiso para document_ocr:read:created_at'),

('document_ocr:create',             'document_ocr', 'create', 'Permiso para document_ocr:create'),
('document_ocr:create:raw_text',    'document_ocr', 'create', 'Permiso para document_ocr:create:raw_text'),
('document_ocr:create:datos_estructurados', 'document_ocr', 'create', 'Permiso para document_ocr:create:datos_estructurados'),
('document_ocr:create:confidence_score',    'document_ocr', 'create', 'Permiso para document_ocr:create:confidence_score'),
('document_ocr:create:pages_processed',     'document_ocr', 'create', 'Permiso para document_ocr:create:pages_processed'),
('document_ocr:create:file_type',   'document_ocr', 'create', 'Permiso para document_ocr:create:file_type'),

('document_ocr:update',           'document_ocr', 'update', 'Permiso para document_ocr:update'),
('document_ocr:update:raw_text',  'document_ocr', 'update', 'Permiso para document_ocr:update:raw_text'),
('document_ocr:update:datos_estructurados', 'document_ocr', 'update', 'Permiso para document_ocr:update:datos_estructurados'),
('document_ocr:update:confidence_score',    'document_ocr', 'update', 'Permiso para document_ocr:update:confidence_score'),
('document_ocr:update:pages_processed',     'document_ocr', 'update', 'Permiso para document_ocr:update:pages_processed'),
('document_ocr:update:file_type', 'document_ocr', 'update', 'Permiso para document_ocr:update:file_type'),

('document_ocr:delete', 'document_ocr', 'delete', 'Permiso para document_ocr:delete'),

-- ################ Template ################
('template:read',            'template', 'read', 'Permiso para template:read'),
('template:read:id',         'template', 'read', 'Permiso para template:read:id'),
('template:read:name',       'template', 'read', 'Permiso para template:read:name'),
('template:read:description','template', 'read', 'Permiso para template:read:description'),
('template:read:ui_schema',  'template', 'read', 'Permiso para template:read:ui_schema'),
('template:read:is_active',  'template', 'read', 'Permiso para template:read:is_active'),
('template:read:created_at', 'template', 'read', 'Permiso para template:read:created_at'),
('template:read:updated_at', 'template', 'read', 'Permiso para template:read:updated_at'),

('template:create',      'template', 'create', 'Permiso para template:create'),
('template:create:name', 'template', 'create', 'Permiso para template:create:name'),
('template:create:description', 'template', 'create', 'Permiso para template:create:description'),

('template:update',      'template', 'update', 'Permiso para template:update'),
('template:update:name', 'template', 'update', 'Permiso para template:update:name'),
('template:update:description', 'template', 'update', 'Permiso para template:update:description'),
('template:update:ui_schema',   'template', 'update', 'Permiso para template:update:ui_schema'),
('template:update:is_active',   'template', 'update', 'Permiso para template:update:is_active'),

('template:delete', 'template', 'delete', 'Permiso para template:delete'),

-- ################ Report Template ################
('report:read',             'report', 'read', 'Permiso para report:read'),
('report:read:id',          'report', 'read', 'Permiso para report:read:id'),
('report:read:owner_id',    'report', 'read', 'Permiso para report:read:owner_id'),
('report:read:name',        'report', 'read', 'Permiso para report:read:name'),
('report:read:description', 'report', 'read', 'Permiso para report:read:description'),
('report:read:department',  'report', 'read', 'Permiso para report:read:department'),
('report:read:report_type', 'report', 'read', 'Permiso para report:read:report_type'),
('report:read:selected_fields', 'report', 'read', 'Permiso para report:read:selected_fields'),
('report:read:filters',     'report', 'read', 'Permiso para report:read:filters'),
('report:read:sort_field',  'report', 'read', 'Permiso para report:read:sort_field'),
('report:read:sort_order',  'report', 'read', 'Permiso para report:read:sort_order'),
('report:read:is_shared',   'report', 'read', 'Permiso para report:read:is_shared'),
('report:read:created_at',  'report', 'read', 'Permiso para report:read:created_at'),
('report:read:updated_at',  'report', 'read', 'Permiso para report:read:updated_at'),

('report:create',             'report', 'create', 'Permiso para report:create'),
('report:create:description', 'report', 'create', 'Permiso para report:create:description'),
('report:create:department',  'report', 'create', 'Permiso para report:create:department'),
('report:create:filters',     'report', 'create', 'Permiso para report:create:filters'),
('report:create:sort_field',  'report', 'create', 'Permiso para report:create:sort_field'),
('report:create:sort_order',  'report', 'create', 'Permiso para report:create:sort_order'),
('report:create:is_shared',   'report', 'create', 'Permiso para report:create:is_shared'),

('report:update',             'report', 'update', 'Permiso para report:update'),
('report:update:name',        'report', 'update', 'Permiso para report:update:name'),
('report:update:description', 'report', 'update', 'Permiso para report:update:description'),
('report:update:department',  'report', 'update', 'Permiso para report:update:department'),
('report:update:report_type', 'report', 'update', 'Permiso para report:update:report_type'),
('report:update:selected_fields', 'report', 'update', 'Permiso para report:update:selected_fields'),
('report:update:filters',     'report', 'update', 'Permiso para report:update:filters'),
('report:update:sort_field',  'report', 'update', 'Permiso para report:update:sort_field'),
('report:update:sort_order',  'report', 'update', 'Permiso para report:update:sort_order'),
('report:update:is_shared',   'report', 'update', 'Permiso para report:update:is_shared'),

('report:delete', 'report', 'delete', 'Permiso para report:delete'),

-- ################ DICOM ################
('dicom:read',                    'dicom', 'read', 'Permiso para dicom:read'),
('dicom:read:study_instance_uid', 'dicom', 'read', 'Permiso para dicom:read:study_instance_uid'),
('dicom:read:study_date',         'dicom', 'read', 'Permiso para dicom:read:study_date'),
('dicom:read:study_description',  'dicom', 'read', 'Permiso para dicom:read:study_description'),
('dicom:read:accession_number',   'dicom', 'read', 'Permiso para dicom:read:accession_number'),
('dicom:read:series_instance_uid', 'dicom', 'read', 'Permiso para dicom:read:series_instance_uid'),
('dicom:read:modality',      'dicom',  'read', 'Permiso para dicom:read:modality'),
('dicom:read:series_number', 'dicom', 'read', 'Permiso para dicom:read:series_number'),
('dicom:read:series_description', 'dicom', 'read', 'Permiso para dicom:read:series_description'),
('dicom:read:body_part',        'dicom', 'read', 'Permiso para dicom:read:body_part'),
('dicom:read:sop_instance_uid', 'dicom', 'read', 'Permiso para dicom:read:sop_instance_uid'),
('dicom:read:instance_number',  'dicom', 'read', 'Permiso para dicom:read:instance_number'),
('dicom:read:file',             'dicom', 'read', 'Permiso para dicom:read:file'),
('dicom:read:metadata',         'dicom', 'read', 'Permiso para dicom:read:metadata'),

('dicom:create',                   'dicom', 'create', 'Permiso para dicom:create'),
('dicom:create:study_date',        'dicom', 'create', 'Permiso para dicom:create:study_date'),
('dicom:create:study_description', 'dicom', 'create', 'Permiso para dicom:create:study_description'),
('dicom:create:accession_number',  'dicom', 'create', 'Permiso para dicom:create:accession_number'),
('dicom:create:series_number',     'dicom', 'create', 'Permiso para dicom:create:series_number'),
('dicom:create:series_description', 'dicom', 'create', 'Permiso para dicom:create:series_description'),
('dicom:create:body_part',       'dicom', 'create', 'Permiso para dicom:create:body_part'),
('dicom:create:instance_number', 'dicom', 'create', 'Permiso para dicom:create:instance_number'),
('dicom:create:metadata',        'dicom', 'create', 'Permiso para dicom:create:metadata'),

('dicom:update',                    'dicom', 'update', 'Permiso para dicom:update'),
('dicom:update:study_date',         'dicom', 'update', 'Permiso para dicom:update:study_date'),
('dicom:update:study_description',  'dicom', 'update', 'Permiso para dicom:update:study_description'),
('dicom:update:accession_number',   'dicom', 'update', 'Permiso para dicom:update:accession_number'),
('dicom:update:series_number',      'dicom', 'update', 'Permiso para dicom:update:series_number'),
('dicom:update:series_description', 'dicom', 'update', 'Permiso para dicom:update:series_description'),
('dicom:update:body_part',       'dicom', 'update', 'Permiso para dicom:update:body_part'),
('dicom:update:instance_number', 'dicom', 'update', 'Permiso para dicom:update:instance_number'),
('dicom:update:metadata',        'dicom', 'update', 'Permiso para dicom:update:metadata'),

('dicom:delete', 'dicom', 'delete', 'Permiso para dicom:delete')
ON CONFLICT (name) DO NOTHING;
